title: Allison Kittinger's Project Portfolio # your name (or website title) here
logo: "/images/newpicrealsq.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome to my portfolio of digital projects! 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
